services:
  translatable_criteria_test_db:
    image: mysql:latest
    container_name: test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '${MYSQL_PORT:-3307}:3306'
